repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt with uv
        entry: sh -c "uv pip freeze > requirements.txt && git add requirements.txt"
        language: system
        types: [python]
