[project]
name = "free-translate-api"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==4.1.3",
    "googletrans==3.1.0a0",
    "python-dotenv>=1.1.1",

]

